"""ADD created_at field

Revision ID: 66632b5d4008
Revises: 13a1cde68db5
Create Date: 2025-01-26 07:30:47.261642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66632b5d4008'
down_revision: Union[str, None] = '13a1cde68db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tron_api_tron_address_info', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tron_api_tron_address_info', 'created_at')
    # ### end Alembic commands ###
